package com.example.model

data class Country(
    val name: String,
    val code: String,
    val flag: String,
    val language: String
)

object CountryData {
    val countries = listOf(
        Country("Afghanistan", "AF", "🇦🇫", "Add primary language"),
        Country("Albania", "AL", "🇦🇱", "Add primary language"),
        Country("Algeria", "DZ", "🇩🇿", "Add primary language"),
        Country("American Samoa", "AS", "🇦🇸", "Add primary language"),
        Country("Andorra", "AD", "🇦🇩", "Add primary language"),
        Country("Angola", "AO", "🇦🇴", "Add primary language"),
        Country("Anguilla", "AI", "🇦🇮", "Add primary language"),
        Country("Antarctica", "AQ", "🇦🇶", "Add primary language"),
        Country("Antigua and Barbuda", "AG", "🇦🇬", "Add primary language"),
        Country("Argentina", "AR", "🇦🇷", "Add primary language"),
        Country("Armenia", "AM", "🇦🇲", "Add primary language"),
        Country("Aruba", "AW", "🇦🇼", "Add primary language"),
        Country("Australia", "AU", "🇦🇺", "Add primary language"),
        Country("Austria", "AT", "🇦🇹", "Add primary language"),
        Country("Azerbaijan", "AZ", "🇦🇿", "Add primary language"),
        Country("Bahamas", "BS", "🇧🇸", "Add primary language"),
        Country("Bahrain", "BH", "🇧🇭", "Add primary language"),
        Country("Bangladesh", "BD", "🇧🇩", "Add primary language"),
        Country("Barbados", "BB", "🇧🇧", "Add primary language"),
        Country("Belarus", "BY", "🇧🇾", "Add primary language"),
        Country("Belgium", "BE", "🇧🇪", "Add primary language"),
        Country("Belize", "BZ", "🇧🇿", "Add primary language"),
        Country("Benin", "BJ", "🇧🇯", "Add primary language"),
        Country("Bermuda", "BM", "🇧🇲", "Add primary language"),
        Country("Bhutan", "BT", "🇧🇹", "Add primary language"),
        Country("Bolivia, Plurinational State of", "BO", "🇧🇴", "Add primary language"),
        Country("Bonaire, Sint Eustatius and Saba", "BQ", "🇧🇶", "Add primary language"),
        Country("Bosnia and Herzegovina", "BA", "🇧🇦", "Add primary language"),
        Country("Botswana", "BW", "🇧🇼", "Add primary language"),
        Country("Bouvet Island", "BV", "🇧🇻", "Add primary language"),
        Country("Brazil", "BR", "🇧🇷", "Add primary language"),
        Country("British Indian Ocean Territory", "IO", "🇮🇴", "Add primary language"),
        Country("Brunei Darussalam", "BN", "🇧🇳", "Add primary language"),
        Country("Bulgaria", "BG", "🇧🇬", "Add primary language"),
        Country("Burkina Faso", "BF", "🇧🇫", "Add primary language"),
        Country("Burundi", "BI", "🇧🇮", "Add primary language"),
        Country("Cabo Verde", "CV", "🇨🇻", "Add primary language"),
        Country("Cambodia", "KH", "🇰🇭", "Add primary language"),
        Country("Cameroon", "CM", "🇨🇲", "Add primary language"),
        Country("Canada", "CA", "🇨🇦", "Add primary language"),
        Country("Cayman Islands", "KY", "🇰🇾", "Add primary language"),
        Country("Central African Republic", "CF", "🇨🇫", "Add primary language"),
        Country("Chad", "TD", "🇹🇩", "Add primary language"),
        Country("Chile", "CL", "🇨🇱", "Add primary language"),
        Country("China", "CN", "🇨🇳", "Add primary language"),
        Country("Christmas Island", "CX", "🇨🇽", "Add primary language"),
        Country("Cocos (Keeling) Islands", "CC", "🇨🇨", "Add primary language"),
        Country("Colombia", "CO", "🇨🇴", "Add primary language"),
        Country("Comoros", "KM", "🇰🇲", "Add primary language"),
        Country("Congo", "CG", "🇨🇬", "Add primary language"),
        Country("Congo, The Democratic Republic of the", "CD", "🇨🇩", "Add primary language"),
        Country("Cook Islands", "CK", "🇨🇰", "Add primary language"),
        Country("Costa Rica", "CR", "🇨🇷", "Add primary language"),
        Country("Croatia", "HR", "🇭🇷", "Add primary language"),
        Country("Cuba", "CU", "🇨🇺", "Add primary language"),
        Country("Curaçao", "CW", "🇨🇼", "Add primary language"),
        Country("Cyprus", "CY", "🇨🇾", "Add primary language"),
        Country("Czechia", "CZ", "🇨🇿", "Add primary language"),
        Country("Côte d'Ivoire", "CI", "🇨🇮", "Add primary language"),
        Country("Denmark", "DK", "🇩🇰", "Add primary language"),
        Country("Djibouti", "DJ", "🇩🇯", "Add primary language"),
        Country("Dominica", "DM", "🇩🇲", "Add primary language"),
        Country("Dominican Republic", "DO", "🇩🇴", "Add primary language"),
        Country("Ecuador", "EC", "🇪🇨", "Add primary language"),
        Country("Egypt", "EG", "🇪🇬", "Add primary language"),
        Country("El Salvador", "SV", "🇸🇻", "Add primary language"),
        Country("Equatorial Guinea", "GQ", "🇬🇶", "Add primary language"),
        Country("Eritrea", "ER", "🇪🇷", "Add primary language"),
        Country("Estonia", "EE", "🇪🇪", "Add primary language"),
        Country("Eswatini", "SZ", "🇸🇿", "Add primary language"),
        Country("Ethiopia", "ET", "🇪🇹", "Add primary language"),
        Country("Falkland Islands (Malvinas)", "FK", "🇫🇰", "Add primary language"),
        Country("Faroe Islands", "FO", "🇫🇴", "Add primary language"),
        Country("Fiji", "FJ", "🇫🇯", "Add primary language"),
        Country("Finland", "FI", "🇫🇮", "Add primary language"),
        Country("France", "FR", "🇫🇷", "Add primary language"),
        Country("French Guiana", "GF", "🇬🇫", "Add primary language"),
        Country("French Polynesia", "PF", "🇵🇫", "Add primary language"),
        Country("French Southern Territories", "TF", "🇹🇫", "Add primary language"),
        Country("Gabon", "GA", "🇬🇦", "Add primary language"),
        Country("Gambia", "GM", "🇬🇲", "Add primary language"),
        Country("Georgia", "GE", "🇬🇪", "Add primary language"),
        Country("Germany", "DE", "🇩🇪", "Add primary language"),
        Country("Ghana", "GH", "🇬🇭", "Add primary language"),
        Country("Gibraltar", "GI", "🇬🇮", "Add primary language"),
        Country("Greece", "GR", "🇬🇷", "Add primary language"),
        Country("Greenland", "GL", "🇬🇱", "Add primary language"),
        Country("Grenada", "GD", "🇬🇩", "Add primary language"),
        Country("Guadeloupe", "GP", "🇬🇵", "Add primary language"),
        Country("Guam", "GU", "🇬🇺", "Add primary language"),
        Country("Guatemala", "GT", "🇬🇹", "Add primary language"),
        Country("Guernsey", "GG", "🇬🇬", "Add primary language"),
        Country("Guinea", "GN", "🇬🇳", "Add primary language"),
        Country("Guinea-Bissau", "GW", "🇬🇼", "Add primary language"),
        Country("Guyana", "GY", "🇬🇾", "Add primary language"),
        Country("Haiti", "HT", "🇭🇹", "Add primary language"),
        Country("Heard Island and McDonald Islands", "HM", "🇭🇲", "Add primary language"),
        Country("Holy See (Vatican City State)", "VA", "🇻🇦", "Add primary language"),
        Country("Honduras", "HN", "🇭🇳", "Add primary language"),
        Country("Hong Kong", "HK", "🇭🇰", "Add primary language"),
        Country("Hungary", "HU", "🇭🇺", "Add primary language"),
        Country("Iceland", "IS", "🇮🇸", "Add primary language"),
        Country("India", "IN", "🇮🇳", "Add primary language"),
        Country("Indonesia", "ID", "🇮🇩", "Add primary language"),
        Country("Iran, Islamic Republic of", "IR", "🇮🇷", "Add primary language"),
        Country("Iraq", "IQ", "🇮🇶", "Add primary language"),
        Country("Ireland", "IE", "🇮🇪", "Add primary language"),
        Country("Isle of Man", "IM", "🇮🇲", "Add primary language"),
        Country("Israel", "IL", "🇮🇱", "Add primary language"),
        Country("Italy", "IT", "🇮🇹", "Add primary language"),
        Country("Jamaica", "JM", "🇯🇲", "Add primary language"),
        Country("Japan", "JP", "🇯🇵", "Add primary language"),
        Country("Jersey", "JE", "🇯🇪", "Add primary language"),
        Country("Jordan", "JO", "🇯🇴", "Add primary language"),
        Country("Kazakhstan", "KZ", "🇰🇿", "Add primary language"),
        Country("Kenya", "KE", "🇰🇪", "Add primary language"),
        Country("Kiribati", "KI", "🇰🇮", "Add primary language"),
        Country("Korea, Democratic People's Republic of", "KP", "🇰🇵", "Add primary language"),
        Country("Korea, Republic of", "KR", "🇰🇷", "Add primary language"),
        Country("Kuwait", "KW", "🇰🇼", "Add primary language"),
        Country("Kyrgyzstan", "KG", "🇰🇬", "Add primary language"),
        Country("Lao People's Democratic Republic", "LA", "🇱🇦", "Add primary language"),
        Country("Latvia", "LV", "🇱🇻", "Add primary language"),
        Country("Lebanon", "LB", "🇱🇧", "Add primary language"),
        Country("Lesotho", "LS", "🇱🇸", "Add primary language"),
        Country("Liberia", "LR", "🇱🇷", "Add primary language"),
        Country("Libya", "LY", "🇱🇾", "Add primary language"),
        Country("Liechtenstein", "LI", "🇱🇮", "Add primary language"),
        Country("Lithuania", "LT", "🇱🇹", "Add primary language"),
        Country("Luxembourg", "LU", "🇱🇺", "Add primary language"),
        Country("Macao", "MO", "🇲🇴", "Add primary language"),
        Country("Madagascar", "MG", "🇲🇬", "Add primary language"),
        Country("Malawi", "MW", "🇲🇼", "Add primary language"),
        Country("Malaysia", "MY", "🇲🇾", "Add primary language"),
        Country("Maldives", "MV", "🇲🇻", "Add primary language"),
        Country("Mali", "ML", "🇲🇱", "Add primary language"),
        Country("Malta", "MT", "🇲🇹", "Add primary language"),
        Country("Marshall Islands", "MH", "🇲🇭", "Add primary language"),
        Country("Martinique", "MQ", "🇲🇶", "Add primary language"),
        Country("Mauritania", "MR", "🇲🇷", "Add primary language"),
        Country("Mauritius", "MU", "🇲🇺", "Add primary language"),
        Country("Mayotte", "YT", "🇾🇹", "Add primary language"),
        Country("Mexico", "MX", "🇲🇽", "Add primary language"),
        Country("Micronesia, Federated States of", "FM", "🇫🇲", "Add primary language"),
        Country("Moldova, Republic of", "MD", "🇲🇩", "Add primary language"),
        Country("Monaco", "MC", "🇲🇨", "Add primary language"),
        Country("Mongolia", "MN", "🇲🇳", "Add primary language"),
        Country("Montenegro", "ME", "🇲🇪", "Add primary language"),
        Country("Montserrat", "MS", "🇲🇸", "Add primary language"),
        Country("Morocco", "MA", "🇲🇦", "Add primary language"),
        Country("Mozambique", "MZ", "🇲🇿", "Add primary language"),
        Country("Myanmar", "MM", "🇲🇲", "Add primary language"),
        Country("Namibia", "NA", "🇳🇦", "Add primary language"),
        Country("Nauru", "NR", "🇳🇷", "Add primary language"),
        Country("Nepal", "NP", "🇳🇵", "Add primary language"),
        Country("Netherlands", "NL", "🇳🇱", "Add primary language"),
        Country("New Caledonia", "NC", "🇳🇨", "Add primary language"),
        Country("New Zealand", "NZ", "🇳🇿", "Add primary language"),
        Country("Nicaragua", "NI", "🇳🇮", "Add primary language"),
        Country("Niger", "NE", "🇳🇪", "Add primary language"),
        Country("Nigeria", "NG", "🇳🇬", "Add primary language"),
        Country("Niue", "NU", "🇳🇺", "Add primary language"),
        Country("Norfolk Island", "NF", "🇳🇫", "Add primary language"),
        Country("North Macedonia", "MK", "🇲🇰", "Add primary language"),
        Country("Northern Mariana Islands", "MP", "🇲🇵", "Add primary language"),
        Country("Norway", "NO", "🇳🇴", "Add primary language"),
        Country("Oman", "OM", "🇴🇲", "Add primary language"),
        Country("Pakistan", "PK", "🇵🇰", "Add primary language"),
        Country("Palau", "PW", "🇵🇼", "Add primary language"),
        Country("Palestine, State of", "PS", "🇵🇸", "Add primary language"),
        Country("Panama", "PA", "🇵🇦", "Add primary language"),
        Country("Papua New Guinea", "PG", "🇵🇬", "Add primary language"),
        Country("Paraguay", "PY", "🇵🇾", "Add primary language"),
        Country("Peru", "PE", "🇵🇪", "Add primary language"),
        Country("Philippines", "PH", "🇵🇭", "Add primary language"),
        Country("Pitcairn", "PN", "🇵🇳", "Add primary language"),
        Country("Poland", "PL", "🇵🇱", "Add primary language"),
        Country("Portugal", "PT", "🇵🇹", "Add primary language"),
        Country("Puerto Rico", "PR", "🇵🇷", "Add primary language"),
        Country("Qatar", "QA", "🇶🇦", "Add primary language"),
        Country("Romania", "RO", "🇷🇴", "Add primary language"),
        Country("Russian Federation", "RU", "🇷🇺", "Add primary language"),
        Country("Rwanda", "RW", "🇷🇼", "Add primary language"),
        Country("Réunion", "RE", "🇷🇪", "Add primary language"),
        Country("Saint Barthélemy", "BL", "🇧🇱", "Add primary language"),
        Country("Saint Helena, Ascension and Tristan da Cunha", "SH", "🇸🇭", "Add primary language"),
        Country("Saint Kitts and Nevis", "KN", "🇰🇳", "Add primary language"),
        Country("Saint Lucia", "LC", "🇱🇨", "Add primary language"),
        Country("Saint Martin (French part)", "MF", "🇲🇫", "Add primary language"),
        Country("Saint Pierre and Miquelon", "PM", "🇵🇲", "Add primary language"),
        Country("Saint Vincent and the Grenadines", "VC", "🇻🇨", "Add primary language"),
        Country("Samoa", "WS", "🇼🇸", "Add primary language"),
        Country("San Marino", "SM", "🇸🇲", "Add primary language"),
        Country("Sao Tome and Principe", "ST", "🇸🇹", "Add primary language"),
        Country("Saudi Arabia", "SA", "🇸🇦", "Add primary language"),
        Country("Senegal", "SN", "🇸🇳", "Add primary language"),
        Country("Serbia", "RS", "🇷🇸", "Add primary language"),
        Country("Seychelles", "SC", "🇸🇨", "Add primary language"),
        Country("Sierra Leone", "SL", "🇸🇱", "Add primary language"),
        Country("Singapore", "SG", "🇸🇬", "Add primary language"),
        Country("Sint Maarten (Dutch part)", "SX", "🇸🇽", "Add primary language"),
        Country("Slovakia", "SK", "🇸🇰", "Add primary language"),
        Country("Slovenia", "SI", "🇸🇮", "Add primary language"),
        Country("Solomon Islands", "SB", "🇸🇧", "Add primary language"),
        Country("Somalia", "SO", "🇸🇴", "Add primary language"),
        Country("South Africa", "ZA", "🇿🇦", "Add primary language"),
        Country("South Georgia and the South Sandwich Islands", "GS", "🇬🇸", "Add primary language"),
        Country("South Sudan", "SS", "🇸🇸", "Add primary language"),
        Country("Spain", "ES", "🇪🇸", "Add primary language"),
        Country("Sri Lanka", "LK", "🇱🇰", "Add primary language"),
        Country("Sudan", "SD", "🇸🇩", "Add primary language"),
        Country("Suriname", "SR", "🇸🇷", "Add primary language"),
        Country("Svalbard and Jan Mayen", "SJ", "🇸🇯", "Add primary language"),
        Country("Sweden", "SE", "🇸🇪", "Add primary language"),
        Country("Switzerland", "CH", "🇨🇭", "Add primary language"),
        Country("Syrian Arab Republic", "SY", "🇸🇾", "Add primary language"),
        Country("Taiwan, Province of China", "TW", "🇹🇼", "Add primary language"),
        Country("Tajikistan", "TJ", "🇹🇯", "Add primary language"),
        Country("Tanzania, United Republic of", "TZ", "🇹🇿", "Add primary language"),
        Country("Thailand", "TH", "🇹🇭", "Add primary language"),
        Country("Timor-Leste", "TL", "🇹🇱", "Add primary language"),
        Country("Togo", "TG", "🇹🇬", "Add primary language"),
        Country("Tokelau", "TK", "🇹🇰", "Add primary language"),
        Country("Tonga", "TO", "🇹🇴", "Add primary language"),
        Country("Trinidad and Tobago", "TT", "🇹🇹", "Add primary language"),
        Country("Tunisia", "TN", "🇹🇳", "Add primary language"),
        Country("Turkmenistan", "TM", "🇹🇲", "Add primary language"),
        Country("Turks and Caicos Islands", "TC", "🇹🇨", "Add primary language"),
        Country("Tuvalu", "TV", "🇹🇻", "Add primary language"),
        Country("Türkiye", "TR", "🇹🇷", "Add primary language"),
        Country("Uganda", "UG", "🇺🇬", "Add primary language"),
        Country("Ukraine", "UA", "🇺🇦", "Add primary language"),
        Country("United Arab Emirates", "AE", "🇦🇪", "Add primary language"),
        Country("United Kingdom", "GB", "🇬🇧", "Add primary language"),
        Country("United States", "US", "🇺🇸", "Add primary language"),
        Country("United States Minor Outlying Islands", "UM", "🇺🇲", "Add primary language"),
        Country("Uruguay", "UY", "🇺🇾", "Add primary language"),
        Country("Uzbekistan", "UZ", "🇺🇿", "Add primary language"),
        Country("Vanuatu", "VU", "🇻🇺", "Add primary language"),
        Country("Venezuela, Bolivarian Republic of", "VE", "🇻🇪", "Add primary language"),
        Country("Viet Nam", "VN", "🇻🇳", "Add primary language"),
        Country("Virgin Islands, British", "VG", "🇻🇬", "Add primary language"),
        Country("Virgin Islands, U.S.", "VI", "🇻🇮", "Add primary language"),
        Country("Wallis and Futuna", "WF", "🇼🇫", "Add primary language"),
        Country("Western Sahara", "EH", "🇪🇭", "Add primary language"),
        Country("Yemen", "YE", "🇾🇪", "Add primary language"),
        Country("Zambia", "ZM", "🇿🇲", "Add primary language"),
        Country("Zimbabwe", "ZW", "🇿🇼", "Add primary language"),
        Country("Åland Islands", "AX", "🇦🇽", "Add primary language")
    )
}
