package com.example

data class IslamicName(
    val name: String,
    val meaning: String
)

val boysNamesList = listOf(
    IslamicName("আব্দুল আজিজ", "পরাক্রমশালী আল্লাহর বান্দা"),
    IslamicName("আব্দুল কাদির", "সর্বশক্তিমান আল্লাহর বান্দা"),
    IslamicName("আব্দুল গফফার", "ক্ষমাশীল আল্লাহর বান্দা"),
    IslamicName("আব্দুল মালিক", "রাজাধিরাজ আল্লাহর বান্দা"),
    IslamicName("আব্দুল হাকিম", "প্রজ্ঞাময় আল্লাহর বান্দা"),
    IslamicName("আব্দুল ওয়াদুদ", "ভালোবাসাময় আল্লাহর বান্দা"),
    IslamicName("আব্দুল বাসিত", "প্রশস্তকারী আল্লাহর বান্দা"),
    IslamicName("আব্দুল মজিদ", "মহিমান্বিত আল্লাহর বান্দা"),
    IslamicName("আব্দুল মতিন", "শক্তিশালী আল্লাহর বান্দা"),
    IslamicName("আব্দুল হাই", "চিরঞ্জীব আল্লাহর বান্দা"),
    IslamicName("মুহাম্মদ", "অত্যন্ত প্রশংসিত"),
    IslamicName("আহমাদ", "অধিক প্রশংসিত"),
    IslamicName("মাহমুদ", "প্রশংসিত"),
    IslamicName("মুস্তাফা", "মনোনীত"),
    IslamicName("তাহমিদ", "আল্লাহর প্রশংসা"),
    IslamicName("তাসমীম", "দৃঢ় সংকল্প"),
    IslamicName("রায়হান", "সুগন্ধি ফুল"),
    IslamicName("সালমান", "নিরাপদ, শান্তিপূর্ণ"),
    IslamicName("সাফওয়ান", "বিশুদ্ধ"),
    IslamicName("সাদিক", "সত্যবাদী"),
    IslamicName("সালেহ", "নেককার"),
    IslamicName("ইব্রাহিম", "একজন নবীর নাম"),
    IslamicName("ইসমাইল", "আল্লাহ শুনেছেন"),
    IslamicName("ইসহাক", "আনন্দ"),
    IslamicName("ইয়াকুব", "একজন নবীর নাম"),
    IslamicName("ইউসুফ", "সৌন্দর্য ও উত্তম চরিত্র"),
    IslamicName("আয়ুব", "ধৈর্যশীল নবীর নাম"),
    IslamicName("আদম", "মানবজাতির প্রথম পিতা"),
    IslamicName("নূহ", "একজন নবীর নাম"),
    IslamicName("মুসা", "একজন নবীর নাম"),
    IslamicName("হারুন", "সম্মানিত"),
    IslamicName("দাউদ", "প্রিয়"),
    IslamicName("সুলাইমান", "শান্তিপূর্ণ"),
    IslamicName("জাকারিয়া", "আল্লাহকে স্মরণকারী"),
    IslamicName("ইয়াহইয়া", "জীবন্ত"),
    IslamicName("হামজা", "সাহসী"),
    IslamicName("হাসান", "সুন্দর"),
    IslamicName("হুসাইন", "সুন্দর, উত্তম"),
    IslamicName("আলী", "উচ্চ মর্যাদার"),
    IslamicName("উমর", "দীর্ঘ জীবন"),
    IslamicName("উসমান", "সাহাবির নাম"),
    IslamicName("বিলাল", "সতেজতা"),
    IslamicName("আনাস", "ভালোবাসা, বন্ধুত্ব"),
    IslamicName("আমিন", "বিশ্বস্ত"),
    IslamicName("আরিফ", "জ্ঞানী"),
    IslamicName("আদিল", "ন্যায়পরায়ণ"),
    IslamicName("ফাহিম", "বুদ্ধিমান"),
    IslamicName("ফারহান", "আনন্দিত"),
    IslamicName("ফয়সাল", "বিচারক"),
    IslamicName("রাশিদ", "সঠিক পথে পরিচালিত"),
    IslamicName("রিদওয়ান", "আল্লাহর সন্তুষ্টি"),
    IslamicName("জায়েদ", "বৃদ্ধি"),
    IslamicName("জুবায়ের", "শক্তিশালী"),
    IslamicName("নাবিল", "মহান"),
    IslamicName("নাঈম", "সুখ, শান্তি"),
    IslamicName("নাসির", "সাহায্যকারী"),
    IslamicName("ওয়াসিম", "সুন্দর"),
    IslamicName("ওয়াহিদ", "একক, অনন্য"),
    IslamicName("শাহিন", "রাজকীয় পাখি"),
    IslamicName("শাকির", "কৃতজ্ঞ"),
    IslamicName("তৌহিদ", "আল্লাহর একত্ব"),
    IslamicName("তামিম", "পরিপূর্ণ"),
    IslamicName("তাহির", "পবিত্র"),
    IslamicName("মিরাজ", "উন্নতি, আরোহণ"),
    IslamicName("মাহির", "দক্ষ"),
    IslamicName("মুবিন", "স্পষ্ট"),
    IslamicName("মুনতাসির", "বিজয়ী"),
    IslamicName("মাসুদ", "সৌভাগ্যবান"),
    IslamicName("মাহদি", "সৎপথপ্রাপ্ত"),
    IslamicName("হাদী", "পথপ্রদর্শক"),
    IslamicName("হাফিজ", "সংরক্ষণকারী"),
    IslamicName("হাবিব", "প্রিয়"),
    IslamicName("ইরফান", "জ্ঞান"),
    IslamicName("এহসান", "উত্তম কাজ"),
    IslamicName("সুহাইল", "সহজ, কোমল"),
    IslamicName("আসিফ", "যোগ্য"),
    IslamicName("আকরাম", "সম্মানিত"),
    IslamicName("আসাদ", "সিংহ"),
    IslamicName("আবরার", "ধার্মিক"),
    IslamicName("আফিফ", "পবিত্র"),
    IslamicName("আফনান", "গাছের শাখা"),
    IslamicName("আহসান", "সর্বোত্তম"),
    IslamicName("আনোয়ার", "আলো"),
    IslamicName("আরহাম", "দয়ালু"),
    IslamicName("আতিফ", "স্নেহশীল"),
    IslamicName("বুরহান", "প্রমাণ"),
    IslamicName("দানিয়াল", "বুদ্ধিমান"),
    IslamicName("জাবির", "সান্ত্বনাদাতা"),
    IslamicName("জাওয়াদ", "দানশীল"),
    IslamicName("কামিল", "পরিপূর্ণ"),
    IslamicName("লাবিব", "বুদ্ধিমান"),
    IslamicName("লতিফ", "দয়ালু"),
    IslamicName("মারুফ", "ভালো"),
    IslamicName("মুয়াজ", "সুরক্ষিত"),
    IslamicName("নাফিস", "মূল্যবান"),
    IslamicName("সাবিত", "দৃঢ়"),
    IslamicName("আকিব", "অনুসারী, পরবর্তী"),
    IslamicName("আকিল", "বুদ্ধিমান"),
    IslamicName("আলিফ", "বন্ধুত্বপূর্ণ, প্রথম অক্ষর"),
    IslamicName("আমানুল্লাহ", "আল্লাহর নিরাপত্তা"),
    IslamicName("আমজাদ", "মহান, সম্মানিত"),
    IslamicName("আনিফ", "পবিত্র, মর্যাদাপূর্ণ"),
    IslamicName("আরমান", "আশা, ইচ্ছা"),
    IslamicName("আশরাফ", "সম্মানিত"),
    IslamicName("আতিক", "মুক্ত, সম্মানিত"),
    IslamicName("আযান", "নামাজের আহ্বান"),
    IslamicName("আফজাল", "শ্রেষ্ঠ"),
    IslamicName("আজহার", "উজ্জ্বল"),
    IslamicName("আব্বাস", "সাহসী, সিংহ"),
    IslamicName("আবিদ", "ইবাদতকারী"),
    IslamicName("বাশির", "সুসংবাদদাতা"),
    IslamicName("বাহির", "উজ্জ্বল"),
    IslamicName("বাকির", "জ্ঞানী"),
    IslamicName("বদর", "পূর্ণিমার চাঁদ"),
    IslamicName("বুরাক", "আলো, উজ্জ্বল"),
    IslamicName("বশারত", "সুসংবাদ"),
    IslamicName("দানিশ", "জ্ঞান"),
    IslamicName("দারিস", "শিক্ষার্থী"),
    IslamicName("দিলশাদ", "আনন্দিত হৃদয়"),
    IslamicName("দিয়ান", "বিচারক"),
    IslamicName("দুররানী", "মূল্যবান মুক্তা"),
    IslamicName("এজাজ", "সম্মান"),
    IslamicName("এহতেশাম", "মর্যাদা"),
    IslamicName("ইলহাম", "প্রেরণা"),
    IslamicName("ইমাদ", "ভিত্তি, স্তম্ভ"),
    IslamicName("ইরশাদ", "পথনির্দেশ"),
    IslamicName("ইশফাক", "দয়া"),
    IslamicName("জাহিদ", "সংযমী"),
    IslamicName("জালাল", "গৌরব"),
    IslamicName("জামিল", "সুন্দর"),
    IslamicName("জারিফ", "বুদ্ধিমান"),
    IslamicName("জিয়াদ", "প্রাচুর্য"),
    IslamicName("কাইস", "বুদ্ধিমান"),
    IslamicName("কারিম", "উদার"),
    IslamicName("কাসিম", "বণ্টনকারী"),
    IslamicName("খালিল", "ঘনিষ্ঠ বন্ধু"),
    IslamicName("খুরশিদ", "সূর্য"),
    IslamicName("লায়েক", "যোগ্য"),
    IslamicName("লিয়াকত", "যোগ্যতা"),
    IslamicName("লুকমান", "জ্ঞানী"),
    IslamicName("মাহফুজ", "সংরক্ষিত"),
    IslamicName("মাজিদ", "মহান"),
    IslamicName("মালিক", "রাজা"),
    IslamicName("মারওয়ان", "শক্তিশালী"),
    IslamicName("মিশকাত", "আলোর স্থান"),
    IslamicName("মুস্তাকিম", "সঠিক পথে থাকা"),
    IslamicName("মুসাব", "শক্তিশালী"),
    IslamicName("মুসাদ্দিক", "সত্যায়নকারী"),
    IslamicName("মুতাসিম", "আল্লাহর আশ্রয় গ্রহণকারী"),
    IslamicName("নাদিম", "বন্ধু"),
    IslamicName("নাফি", "উপকারী"),
    IslamicName("নাজিম", "পরিচালক"),
    IslamicName("নওফেল", "দানশীল"),
    IslamicName("নুরুল ইসলাম", "ইসলামের আলো"),
    IslamicName("রাফি", "উচ্চ মর্যাদার"),
    IslamicName("রাকান", "শক্তিশালী"),
    IslamicName("রউফ", "অত্যন্ত দয়ালু"),
    IslamicName("রিয়াদ", "বাগান"),
    IslamicName("রুহান", "আত্মিক"),
    IslamicName("সাবির", "ধৈর্যশীল"),
    IslamicName("সাদমান", "আনন্দিত"),
    IslamicName("সাজিদ", "সিজদাকারী"),
    IslamicName("সাইফ", "তলোয়ার"),
    IslamicName("সালিক", "পথের যাত্রী"),
    IslamicName("সামির", "সঙ্গী"),
    IslamicName("শারিক", "অংশীদার"),
    IslamicName("শিহাব", "উজ্জ্বল নক্ষত্র"),
    IslamicName("তাবিশ", "উজ্জ্বলতা"),
    IslamicName("তাকী", "ধার্মিক"),
    IslamicName("তাসফিন", "বিশুদ্ধ"),
    IslamicName("তাওফিক", "সাফল্য"),
    IslamicName("তানজিম", "সাজানো"),
    IslamicName("উবায়দ", "আল্লাহর বান্দা"),
    IslamicName("উমাইর", "বুদ্ধিমান"),
    IslamicName("উসামা", "সিংহ"),
    IslamicName("ওয়াসিল", "সম্পর্ক স্থাপনকারী"),
    IslamicName("ইয়ামান", "সৌভাগ্যবান"),
    IslamicName("ইয়াকীন", "বিশ্বাস"),
    IslamicName("জাহান", "বিশ্ব"),
    IslamicName("ফারিস", "অশ্বারোহী"),
    IslamicName("ফাহাদ", "চিতাবাঘ"),
    IslamicName("ফিরোজ", "বিজয়ী"),
    IslamicName("ফুয়াদ", "হৃদয়"),
    IslamicName("হানিফ", "সত্যপথের অনুসারী"),
    IslamicName("হাসিব", "সম্মানিত"),
    IslamicName("হিলাল", "নতুন চাঁদ"),
    IslamicName("হুমায়ুন", "সৌভাগ্যবান"),
    IslamicName("ইমতিয়াজ", "বিশেষত্ব"),
    IslamicName("রাশাদ", "সঠিক পথ"),
    IslamicName("তাহসিন", "সুন্দর করা"),
    IslamicName("মুকিত", "রক্ষাকারী"),
    IslamicName("নাবিহ", "বুদ্ধিমান"),
    IslamicName("সিরাজ", "প্রদীপ, আলো"),
    IslamicName("শরীফ", "সম্মানিত"),
    IslamicName("জারার", "সাহসী"),
    IslamicName("ফখরুল", "গৌরবের অধিকারী"),
    IslamicName("হারিস", "রক্ষক"),
    IslamicName("আদনান", "স্থায়ী বাসিন্দা"),
    IslamicName("আবরাহা", "সম্মানিত ব্যক্তি"),
    IslamicName("আফসার", "নেতা, প্রধান"),
    IslamicName("আলভী", "উচ্চ মর্যাদার"),
    IslamicName("আমান", "নিরাপত্তা, শান্তি"),
    IslamicName("আনসার", "সহায়তাকারী"),
    IslamicName("আরশ", "সিংহাসন"),
    IslamicName("আসফাক", "দয়ালু"),
    IslamicName("আতহার", "অত্যন্ত পবিত্র"),
    IslamicName("আবদুর রশিদ", "সঠিক পথপ্রাপ্ত"),
    IslamicName("বাহার", "বসন্ত"),
    IslamicName("বাশার", "মানুষ"),
    IslamicName("বদিউজ্জামান", "সময়ের বিস্ময়"),
    IslamicName("বাকী", "চিরস্থায়ী"),
    IslamicName("বুরহানুল্লাহ", "আল্লাহর প্রমাণ"),
    IslamicName("দারিয়ান", "জ্ঞানী"),
    IslamicName("দিলওয়ার", "সাহসী হৃদয়"),
    IslamicName("দিশান", "দিকনির্দেশ"),
    IslamicName("একরাম", "সম্মান"),
    IslamicName("এমরান", "উন্নতি, সমৃদ্ধি"),
    IslamicName("ইবাদ", "বান্দারা"),
    IslamicName("ইজাজ", "অলৌকিকতা"),
    IslamicName("ইলিয়াস", "একজন নবীর নাম"),
    IslamicName("ইনায়েত", "অনুগ্রহ"),
    IslamicName("ইশতিয়াক", "আকাঙ্ক্ষা"),
    IslamicName("জাবেদ", "চিরস্থায়ী"),
    IslamicName("জাফর", "বিজয়ী"),
    IslamicName("জাইনুল", "সৌন্দর্যের অধিকারী"),
    IslamicName("জুনায়েদ", "সৈনিক"),
    IslamicName("জুলকারনাইন", "শক্তিশালী ব্যক্তি"),
    IslamicName("কামরান", "সফল, সৌভাগ্যবান"),
    IslamicName("কুদরত", "ক্ষমতা"),
    IslamicName("খাইরুল", "উত্তম"),
    IslamicName("খুররম", "আনন্দিত"),
    IslamicName("মাহবুব", "প্রিয়"),
    IslamicName("মাকসুদ", "উদ্দেশ্য"),
    IslamicName("মাসুম", "নিষ্পাপ"),
    IslamicName("মুবাশশির", "সুসংবাদদাতা"),
    IslamicName("মুহাইমিন", "রক্ষাকারী"),
    IslamicName("মুনির", "আলোকিত"),
    IslamicName("মুরাদ", "ইচ্ছা"),
    IslamicName("নাসিম", "হালকা বাতাস"),
    IslamicName("নওশাদ", "আনন্দিত"),
    IslamicName("নিয়াজ", "প্রার্থনা"),
    IslamicName("রাফাত", "দয়া"),
    IslamicName("রায়েদ", "নেতা"),
    IslamicName("রাকিব", "পর্যবেক্ষক"),
    IslamicName("রাশান", "উজ্জ্বল"),
    IslamicName("রুমান", "সুন্দর"),
    IslamicName("সাফি", "বিশুদ্ধ"),
    IslamicName("সাকিব", "উজ্জ্বল নক্ষত্র"),
    IslamicName("সাইম", "রোজাদার"),
    IslamicName("সারিম", "সাহসী"),
    IslamicName("শাহরিয়ার", "রাজা"),
    IslamicName("শামিম", "সুগন্ধ"),
    IslamicName("তাবারক", "বরকতময়"),
    IslamicName("তালহা", "এক ধরনের গাছ"),
    IslamicName("তালিব", "অনুসন্ধানকারী"),
    IslamicName("তাসিফ", "প্রশংসাকারী"),
    IslamicName("তুরাব", "মাটি"),
    IslamicName("উজায়ের", "সহায়ক"),
    IslamicName("ওয়ালিদ", "নবজাতক"),
    IslamicName("ওয়াকিল", "প্রতিনিধি"),
    IslamicName("ইয়াসির", "সহজ"),
    IslamicName("ইউনুস", "একজন নবীর নাম"),
    IslamicName("জিয়ান", "জীবন"),
    IslamicName("ফারমান", "আদেশ"),
    IslamicName("হামিদ", "প্রশংসাকারী"),
    IslamicName("হাশিম", "দানশীল"),
    IslamicName("হেলাল", "নতুন চাঁদ"),
    IslamicName("হাফস", "সংরক্ষণকারী"),
    IslamicName("আরিফান", "জ্ঞানী"),
    IslamicName("আযহারুল", "উজ্জ্বল"),
    IslamicName("বশীরুল", "সুসংবাদদাতা"),
    IslamicName("দিলশান", "আনন্দিত হৃদয়"),
    IslamicName("ইরফানুল", "জ্ঞানের অধিকারী"),
    IslamicName("জামান", "সময়"),
    IslamicName("কাইফ", "আনন্দ"),
    IslamicName("মাহিন", "চাঁদের মতো"),
    IslamicName("নুহান", "বুদ্ধিমান"),
    IslamicName("সাহিল", "তীর, উপকূল"),
    IslamicName("তাসিন", "কুরআনের অক্ষর"),
    IslamicName("উরফান", "জ্ঞান"),
    IslamicName("ফারহাদ", "আনন্দিত"),
    IslamicName("হাবিবুল্লাহ", "আল্লাহর প্রিয়"),
    IslamicName("রিয়ান", "জান্নাতের দরজা"),
    IslamicName("আবদুল ওয়াহাব", "দানশীল আল্লাহর বান্দা"),
    IslamicName("আবদুল কাইয়ুম", "চিরস্থায়ী আল্লাহর বান্দা"),
    IslamicName("আবদুল লতিফ", "দয়ালু আল্লাহর বান্দা"),
    IslamicName("আবদুল করিম", "মহান দয়ালু আল্লাহর বান্দা"),
    IslamicName("আবদুল হালিম", "সহনশীল আল্লাহর বান্দা"),
    IslamicName("আবদুল গনি", "অমুখাপেক্ষী আল্লাহর বান্দা"),
    IslamicName("আবদুল হাফিজ", "সংরক্ষণকারী আল্লাহর বান্দা"),
    IslamicName("আবদুল বারী", "সৃষ্টিকর্তার বান্দা"),
    IslamicName("আবদুল মুকিত", "রক্ষাকারী আল্লাহর বান্দা"),
    IslamicName("আফরোজ", "আলোকিতকারী"),
    IslamicName("আহিল", "যোগ্য, সক্ষম"),
    IslamicName("আনোয়ারুল", "আলোর অধিকারী"),
    IslamicName("আরশান", "শক্তিশালী"),
    IslamicName("আসিফান", "যোগ্য ব্যক্তি"),
    IslamicName("আতাউর", "দান, উপহার"),
    IslamicName("আযীম", "মহান"),
    IslamicName("আবির", "সুগন্ধ"),
    IslamicName("আলমগীর", "বিশ্বজয়ী"),
    IslamicName("আমানুল", "নিরাপত্তা"),
    IslamicName("বাহিজ", "সুন্দর, আনন্দময়"),
    IslamicName("বাশিরুল", "সুসংবাদদাতা"),
    IslamicName("বদরুল", "পূর্ণিমার চাঁদ"),
    IslamicName("বুরহানুল", "স্পষ্ট প্রমাণ"),
    IslamicName("বিনয়", "নম্রতা"),
    IslamicName("দিলাওয়ার", "সাহসী"),
    IslamicName("দুররুল", "মূল্যবান মুক্তা"),
    IslamicName("এহতেশামুল", "মর্যাদাপূর্ণ"),
    IslamicName("ইমরানুল", "সমৃদ্ধিশালী"),
    IslamicName("ইয়ামিন", "সৌভাগ্যবান"),
    IslamicName("জাবিরুল", "সান্ত্বনাদাতা"),
    IslamicName("জাহিরুল", "উজ্জ্বল"),
    IslamicName("জালালুল", "মহত্ত্ব"),
    IslamicName("জিয়াউল", "আলো"),
    IslamicName("কাইফান", "আনন্দিত"),
    IslamicName("কারিমুল", "উদার"),
    IslamicName("কামরুল", "চাঁদের মতো"),
    IslamicName("খালিলুল্লাহ", "আল্লাহর বন্ধু"),
    IslamicName("লিয়ান", "কোমলতা"),
    IslamicName("মাহিরুল", "দক্ষ"),
    IslamicName("মাহফুজুল", "সংরক্ষিত"),
    IslamicName("মারুফুল", "ভালো কাজের অধিকারী"),
    IslamicName("মাসরুর", "আনন্দিত"),
    IslamicName("মুবাশশিরুল", "সুসংবাদদাতা"),
    IslamicName("মুসতাফিজ", "উপকার গ্রহণকারী"),
    IslamicName("মুজতবা", "নির্বাচিত"),
    IslamicName("নাসিরুল", "সাহায্যকারী"),
    IslamicName("নাজিফ", "পরিষ্কার"),
    IslamicName("নাদির", "বিরল"),
    IslamicName("নুরুল হুদা", "পথনির্দেশের আলো"),
    IslamicName("রাইফ", "দয়ালু"),
    IslamicName("রাফান", "সৌন্দর্যপূর্ণ"),
    IslamicName("রিজভান", "সন্তুষ্টি"),
    IslamicName("রশিদুল", "সঠিক পথের"),
    IslamicName("রওনক", "সৌন্দর্য"),
    IslamicName("সাবান", "পরিষ্কার"),
    IslamicName("সাফওয়ানুল", "বিশুদ্ধ"),
    IslamicName("সাইফুল ইসলাম", "ইসলামের তলোয়ার"),
    IslamicName("সালমানুল", "নিরাপদ"),
    IslamicName("সামিউল", "শ্রবণকারী"),
    IslamicName("শাহেদ", "সাক্ষী"),
    IslamicName("শাহরুখ", "রাজকীয় মুখ"),
    IslamicName("শাফিন", "পবিত্র"),
    IslamicName("তাহসীন", "সুন্দর করা"),
    IslamicName("তামজীদ", "প্রশংসা"),
    IslamicName("তানভীর", "আলোর রশ্মি"),
    IslamicName("তাওসিফ", "প্রশংসা"),
    IslamicName("তুরসান", "শক্তিশালী"),
    IslamicName("উমাইদ", "আশাবাদী"),
    IslamicName("উরাইফ", "জ্ঞানী"),
    IslamicName("ওয়াসিক", "বিশ্বস্ত"),
    IslamicName("ওয়াজিদ", "প্রাপ্তকারী"),
    IslamicName("ফারুকুল", "সত্য-মিথ্যার পার্থক্যকারী"),
    IslamicName("ফয়জান", "অনুগ্রহ"),
    IslamicName("হাদিয়ান", "পথপ্রদর্শক"),
    IslamicName("হামদান", "প্রশংসাকারী"),
    IslamicName("হারিসান", "রক্ষক"),
    IslamicName("হুসাম", "তলোয়ার"),
    IslamicName("ইলহান", "অনুপ্রেরণা"),
    IslamicName("মিরান", "রাজপুত্র"),
    IslamicName("সিরাজুল", "আলোর প্রদীপ"),
    IslamicName("তালহান", "গাছের নাম"),
    IslamicName("জায়ন", "সৌন্দর্য"),
    IslamicName("মুনতাজিম", "সুশৃঙ্খল"),
    IslamicName("নুহাইল", "ছোট সুন্দর"),
    IslamicName("আসাদুল্লাহ", "আল্লাহর সিংহ"),
    IslamicName("মাহবুবুল্লাহ", "আল্লাহর প্রিয়"),
    IslamicName("রুহানুল", "আত্মিক"),
    IslamicName("সুহান", "সুন্দর"),
    IslamicName("ইহসানুল", "উত্তম কাজ"),
    IslamicName("আবদুল আহাদ", "এক আল্লাহর বান্দা"),
    IslamicName("আবদুস সালাম", "শান্তিদাতা আল্লাহর বান্দা"),
    IslamicName("আবদুর রউফ", "অত্যন্ত দয়ালু আল্লাহর বান্দা"),
    IslamicName("আবদুস সামাদ", "অমুখাপেক্ষী আল্লাহর বান্দা"),
    IslamicName("আবদুল আজিম", "মহান আল্লাহর বান্দা"),
    IslamicName("আবদুল ওয়াকিল", "অভিভাবক আল্লাহর বান্দা"),
    IslamicName("আবদুল মুমিন", "বিশ্বাসদাতা আল্লাহর বান্দা"),
    IslamicName("আবদুল মুকাদ্দিম", "অগ্রসরকারী আল্লাহর বান্দা"),
    IslamicName("আবদুল নূর", "আলোর আল্লাহর বান্দা"),
    IslamicName("আবদুল হাদি", "পথপ্রদর্শক আল্লাহর বান্দা"),
    IslamicName("আফনানুল", "শাখা-প্রশাখার মতো সুন্দর"),
    IslamicName("আহমের", "লালচে, সুন্দর"),
    IslamicName("আকদাস", "অত্যন্ত পবিত্র"),
    IslamicName("আলমীন", "বিশ্বস্ত"),
    IslamicName("আনজুম", "তারকা"),
    IslamicName("আরশাদ", "সঠিক পথপ্রাপ্ত"),
    IslamicName("আসকার", "সৈনিক"),
    IslamicName("আতহারুল", "পবিত্রতম"),
    IslamicName("আযানুল", "আহ্বান"),
    IslamicName("আবদীন", "ইবাদতকারী"),
    IslamicName("বাহমান", "ভালো মন"),
    IslamicName("বদরুল ইসলাম", "ইসলামের পূর্ণিমার চাঁদ"),
    IslamicName("বাকিব", "স্থায়ী"),
    IslamicName("বশারুল", "সুসংবাদ"),
    IslamicName("বুরহানুদ্দিন", "ধর্মের প্রমাণ"),
    IslamicName("দাবির", "লেখক, জ্ঞানী"),
    IslamicName("দারিয়াব", "সমুদ্রের মতো বিশাল"),
    IslamicName("দিলনওয়াজ", "হৃদয় জয়কারী"),
    IslamicName("দিশার", "পথ দেখানো"),
    IslamicName("এজাজুল", "সম্মানের অধিকারী"),
    IslamicName("ইকরামুল", "সম্মানিত"),
    IslamicName("ইশরাক", "সূর্যের আলো"),
    IslamicName("ইলহামুল", "প্রেরণাদায়ক"),
    IslamicName("ইনামুল", "উপহার"),
    IslamicName("জাহিদুল", "ধার্মিক"),
    IslamicName("জামিলুল", "সুন্দর"),
    IslamicName("জিয়াউদ্দিন", "ধর্মের আলো"),
    IslamicName("জুনায়ের", "ছোট সৈনিক"),
    IslamicName("কাদির", "শক্তিশালী"),
    IslamicName("কাইয়ুম", "চিরস্থায়ী"),
    IslamicName("কামাল", "পরিপূর্ণতা"),
    IslamicName("খালিস", "বিশুদ্ধ"),
    IslamicName("লতিফুল", "দয়ালু"),
    IslamicName("মাহবুর", "প্রিয়"),
    IslamicName("মাহিরান", "দক্ষ"),
    IslamicName("মাইদান", "ক্ষেত্র"),
    IslamicName("মুনাওয়ার", "আলোকিত"),
    IslamicName("মুরশিদ", "পথপ্রদর্শক"),
    IslamicName("মুসাফির", "ভ্রমণকারী"),
    IslamicName("মুজাহিদুল", "সংগ্রামী"),
    IslamicName("নাজমুল", "তারকা"),
    IslamicName("নাসিরুদ্দিন", "ধর্মের সাহায্যকারী"),
    IslamicName("নওমানুল", "সুন্দর"),
    IslamicName("নূরুল্লাহ", "আল্লাহর আলো"),
    IslamicName("রফিক", "বন্ধু"),
    IslamicName("রায়হানুল", "সুগন্ধি"),
    IslamicName("রাকিবুল", "পর্যবেক্ষক"),
    IslamicName("রাশেদ", "সঠিক পথে থাকা"),
    IslamicName("রুহুল", "আত্মা"),
    IslamicName("সাদাত", "সৌভাগ্য"),
    IslamicName("সাফাত", "পবিত্রতা"),
    IslamicName("সাইফুল্লাহ", "আল্লাহর তলোয়ার"),
    IslamicName("সালেহুল", "সৎ"),
    IslamicName("সামাদ", "অমুখাপেক্ষী"),
    IslamicName("শাহরিয়ারুল", "রাজকীয়"),
    IslamicName("শাফায়াত", "সুপারিশ"),
    IslamicName("শরিফুল", "সম্মানিত"),
    IslamicName("তাকরিম", "সম্মান"),
    IslamicName("তাহমাস", "সাহসী"),
    IslamicName("তাসাওয়ার", "চিন্তা"),
    IslamicName("তাজিম", "সম্মান"),
    IslamicName("তানজিল", "অবতীর্ণ"),
    IslamicName("উবাই", "সম্মানিত"),
    IslamicName("উমারান", "সমৃদ্ধি"),
    IslamicName("ওয়াজিহ", "সম্মানিত"),
    IslamicName("ওয়ালিহ", "আনন্দিত"),
    IslamicName("ইয়াসিরুল", "সহজ"),
    IslamicName("ফারহানুল", "আনন্দিত"),
    IslamicName("ফয়সালুল", "বিচারক"),
    IslamicName("ফজল", "অনুগ্রহ"),
    IslamicName("ফিরদাউস", "জান্নাত"),
    IslamicName("হামিদুল", "প্রশংসাকারী"),
    IslamicName("হাসিবুল", "সম্মানিত"),
    IslamicName("হায়দার", "সিংহ"),
    IslamicName("হুসামুদ্দিন", "ধর্মের তলোয়ার"),
    IslamicName("ইরফানুল্লাহ", "আল্লাহর জ্ঞান"),
    IslamicName("মাহদি হাসান", "সৎপথপ্রাপ্ত সুন্দর"),
    IslamicName("রিদওয়ানুল", "সন্তুষ্টি"),
    IslamicName("সিরাজুদ্দিন", "ধর্মের আলো"),
    IslamicName("তৌফিকুল", "সাফল্য"),
    IslamicName("জিয়ানুল", "জীবনের আলো"),
    IslamicName("নূরান", "আলোকিত"),
    IslamicName("মুসফিক", "দয়ালু"),
    IslamicName("সুহানুল", "সুন্দর"),
    IslamicName("আলহাম", "প্রেরণা")
)

val girlsNamesList = listOf(
    IslamicName("আয়েশা", "জীবন্ত, সুখী"),
    IslamicName("খাদিজা", "অকাল জন্মগ্রহণকারী"),
    IslamicName("ফাতিমা", "পবিত্র, সংযমী"),
    IslamicName("হাফসা", "সিংহী"),
    IslamicName("জয়নাব", "সুগন্ধি ফুল"),
    IslamicName("রুকাইয়া", "উন্নত, মর্যাদাবান"),
    IslamicName("উম্মে কুলসুম", "সুন্দর মুখমণ্ডল"),
    IslamicName("আসমা", "উচ্চ মর্যাদাসম্পন্ন"),
    IslamicName("সুমাইয়া", "উচ্চ মর্যাদার"),
    IslamicName("মারিয়াম", "পবিত্র নারী"),
    IslamicName("সাফিয়া", "বিশুদ্ধ, খাঁটি"),
    IslamicName("হালিমা", "ধৈর্যশীলা"),
    IslamicName("আমিনা", "বিশ্বস্ত"),
    IslamicName("রাইহানা", "সুগন্ধি ফুল"),
    IslamicName("নুসাইবা", "সম্মানিত নারী"),
    IslamicName("লুবাবা", "বিশুদ্ধ হৃদয়ের"),
    IslamicName("জুওয়াইরিয়া", "ছোট সুন্দরী"),
    IslamicName("বারিরা", "ধার্মিক"),
    IslamicName("উমাইমা", "ছোট মা"),
    IslamicName("আতিকা", "সম্মানিত"),
    IslamicName("আফরা", "উজ্জ্বল সাদা"),
    IslamicName("আলিয়া", "উচ্চ মর্যাদার"),
    IslamicName("আরিবা", "জ্ঞানী"),
    IslamicName("আরিজা", "সম্মানিত"),
    IslamicName("আনিশা", "বন্ধুসুলভ"),
    IslamicName("আফিয়া", "সুস্থতা"),
    IslamicName("আনিকা", "সুন্দরী"),
    IslamicName("আসমিনা", "মূল্যবান"),
    IslamicName("আদিবা", "ভদ্র, শিক্ষিতা"),
    IslamicName("আফনান", "ফলের শাখা"),
    IslamicName("ইমান", "বিশ্বাস"),
    IslamicName("ইনায়া", "যত্ন, অনুগ্রহ"),
    IslamicName("ইকরা", "পড়ো"),
    IslamicName("ইশরাত", "আনন্দ"),
    IslamicName("ইলমা", "জ্ঞান"),
    IslamicName("তাসনিম", "জান্নাতের ঝর্ণা"),
    IslamicName("তাহিরা", "পবিত্র"),
    IslamicName("তাবাসসুম", "হাসি"),
    IslamicName("তানজিলা", "অবতীর্ণ"),
    IslamicName("তানহা", "একাকী"),
    IslamicName("তামান্না", "আকাঙ্ক্ষা"),
    IslamicName("জান্নাত", "স্বর্গ"),
    IslamicName("জান্নাতুল", "জান্নাতের"),
    IslamicName("জারিন", "সোনালী"),
    IslamicName("জারা", "ফুল"),
    IslamicName("জুনাইরা", "ছোট সুন্দরী"),
    IslamicName("জোহরা", "উজ্জ্বল"),
    IslamicName("জুহা", "সকালবেলা"),
    IslamicName("রাবেয়া", "চতুর্থ"),
    IslamicName("রুকসানা", "উজ্জ্বল মুখ"),
    IslamicName("রিদা", "সন্তুষ্টি"),
    IslamicName("রাফিয়া", "উচ্চ মর্যাদার"),
    IslamicName("রুমাইসা", "ছোট ফুল"),
    IslamicName("রাইসা", "নেত্রী"),
    IslamicName("রাইমা", "সুন্দরী"),
    IslamicName("সাদিয়া", "সৌভাগ্যবতী"),
    IslamicName("সাবিহা", "সুন্দরী"),
    IslamicName("সামিরা", "আড্ডাসঙ্গী"),
    IslamicName("সাবা", "সকালের বাতাস"),
    IslamicName("সাফা", "বিশুদ্ধতা"),
    IslamicName("সুমাইরা", "বাদামী বর্ণের সুন্দরী"),
    IslamicName("সারা", "রাজকুমারী"),
    IslamicName("সিদরা", "জান্নাতের বৃক্ষ"),
    IslamicName("সানজিদা", "গম্ভীর"),
    IslamicName("শারমিন", "লাজুক"),
    IslamicName("শাইলা", "শিষ্টাচারী"),
    IslamicName("শাহিনা", "রাজকীয়"),
    IslamicName("শামিমা", "সুগন্ধ"),
    IslamicName("নাদিয়া", "আহ্বানকারী"),
    IslamicName("নাওয়াল", "উপহার"),
    IslamicName("নাজিফা", "পবিত্র"),
    IslamicName("নাশিদা", "কবিতা আবৃত্তিকারী"),
    IslamicName("নুসরাত", "সাহায্য"),
    IslamicName("নওরীন", "উজ্জ্বল আলো"),
    IslamicName("নাইমা", "শান্তিপূর্ণ"),
    IslamicName("নাবিলা", "মহৎ"),
    IslamicName("মাহিরা", "দক্ষ"),
    IslamicName("মাহজাবিন", "চাঁদের মতো সুন্দর"),
    IslamicName("মারওয়া", "পবিত্র পাহাড়"),
    IslamicName("মুনতাহা", "সর্বোচ্চ সীমা"),
    IslamicName("মালিহা", "সুন্দরী"),
    IslamicName("মেহরিন", "সূর্যের আলো"),
    IslamicName("মাইশা", "সুখী জীবন"),
    IslamicName("হুমায়রা", "লালাভ সুন্দরী"),
    IslamicName("হাবিবা", "প্রিয়"),
    IslamicName("হানা", "সুখ"),
    IslamicName("হুরাইন", "জান্নাতের হুর"),
    IslamicName("ইয়াসমিন", "জুঁই ফুল"),
    IslamicName("লামিয়া", "উজ্জ্বল"),
    IslamicName("লুবনা", "এক ধরনের গাছ"),
    IslamicName("লাইলা", "রাত"),
    IslamicName("মারিয়া", "পবিত্র নারী"),
    IslamicName("আরশিয়া", "উচ্চ মর্যাদার"),
    IslamicName("আলিশবা", "সুন্দরী"),
    IslamicName("আবিদা", "ইবাদতকারী নারী"),
    IslamicName("আবিরা", "সুগন্ধ ছড়ানো"),
    IslamicName("আফসানা", "গল্প, কাহিনী"),
    IslamicName("আফসারী", "সম্মানিত নারী"),
    IslamicName("আহলাম", "স্বপ্নসমূহ"),
    IslamicName("আখতার", "তারা"),
    IslamicName("আলমাস", "হীরা"),
    IslamicName("আলেয়া", "উচ্চ মর্যাদার"),
    IslamicName("আমাতুল্লাহ", "আল্লাহর বান্দী"),
    IslamicName("আমিরা", "রাজকুমারী, নেত্রী"),
    IslamicName("আনফিসা", "মূল্যবান"),
    IslamicName("আনজুমান", "সমাবেশ"),
    IslamicName("আরিবা নূর", "জ্ঞানী আলো"),
    IslamicName("আরশিনা", "সিংহাসনের সাথে সম্পর্কিত"),
    IslamicName("আসিয়া", "সান্ত্বনাদানকারী"),
    IslamicName("আসমাত", "পবিত্রতা"),
    IslamicName("আতিয়া", "উপহার"),
    IslamicName("আযরা", "পবিত্র কুমারী"),
    IslamicName("আনোয়ারা", "আলোকিত"),
    IslamicName("বানু", "সম্মানিত নারী"),
    IslamicName("বাশিরা", "সুসংবাদদাত্রী"),
    IslamicName("বিলকিস", "রানী, সম্মানিত নারী"),
    IslamicName("বুশরা", "সুসংবাদ"),
    IslamicName("দিলরুবা", "হৃদয় জয়কারী"),
    IslamicName("দিলশাদা", "আনন্দিত হৃদয়"),
    IslamicName("দুররিয়া", "মুক্তার মতো উজ্জ্বল"),
    IslamicName("এহসানা", "উত্তম কাজ করা নারী"),
    IslamicName("ইবাদাত", "উপাসনা"),
    IslamicName("ইফফাত", "পবিত্রতা"),
    IslamicName("ইনশিরাহ", "প্রশান্তি"),
    IslamicName("ইরতিজা", "সন্তুষ্টি"),
    IslamicName("ইসরাত", "আনন্দ"),
    IslamicName("ইসমত", "সতীত্ব"),
    IslamicName("ইস্তিবশার", "সুসংবাদে আনন্দ"),
    IslamicName("জানাত", "স্বর্গ"),
    IslamicName("জারিফা", "বুদ্ধিমতী"),
    IslamicName("জাহরা", "উজ্জ্বল ফুল"),
    IslamicName("জুহাইনা", "সুন্দরী"),
    IslamicName("কামিলা", "পরিপূর্ণ"),
    IslamicName("করিমা", "উদার নারী"),
    IslamicName("খানসা", "সুন্দরী নারী"),
    IslamicName("খাদরা", "সবুজ, সতেজ"),
    IslamicName("খালিদা", "চিরস্থায়ী"),
    IslamicName("লতিফা", "কোমল ও দয়ালু"),
    IslamicName("লাবিবা", "বুদ্ধিমতী"),
    IslamicName("লামিসা", "নরম স্পর্শ"),
    IslamicName("লুজাইন", "রূপা"),
    IslamicName("মাহনুর", "চাঁদের আলো"),
    IslamicName("মাহরুখ", "চাঁদের মতো মুখ"),
    IslamicName("মারিয়াহ", "পবিত্র নারী"),
    IslamicName("মাশহুরা", "প্রসিদ্ধ"),
    IslamicName("মাহফুজা", "সংরক্ষিত"),
    IslamicName("মুকাররমা", "সম্মানিত"),
    IslamicName("মুনাওয়ারা", "আলোকিত"),
    IslamicName("মুনিরা", "উজ্জ্বল"),
    IslamicName("মুরশিদা", "পথপ্রদর্শক"),
    IslamicName("নাজওয়া", "গোপন কথা"),
    IslamicName("নাশওয়া", "আনন্দ"),
    IslamicName("নাসিমা", "মৃদু বাতাস"),
    IslamicName("নাজমা", "তারা"),
    IslamicName("নাওমি", "সুখকর"),
    IslamicName("নূরজাহান", "বিশ্বের আলো"),
    IslamicName("নূরাইন", "দুই আলো"),
    IslamicName("নূরিয়া", "আলোকিত"),
    IslamicName("রাহিলা", "ভ্রমণকারী"),
    IslamicName("রাবিহা", "সফল"),
    IslamicName("রাশিদা", "সৎপথপ্রাপ্ত"),
    IslamicName("রুকাইনা", "মর্যাদাশীলা"),
    IslamicName("রুমানা", "ডালিম ফল"),
    IslamicName("রাইদা", "অগ্রগামী"),
    IslamicName("রেহানা", "সুগন্ধি ফুল"),
    IslamicName("সাবরিনা", "ধৈর্যশীলা"),
    IslamicName("সাজিদা", "সিজদাকারিণী"),
    IslamicName("সাকিনা", "প্রশান্তি"),
    IslamicName("সালমা", "নিরাপদ"),
    IslamicName("সামিয়া", "উচ্চ মর্যাদার"),
    IslamicName("সানিয়া", "উজ্জ্বল"),
    IslamicName("সুহানা", "মনোরম"),
    IslamicName("সুরাইয়া", "তারকারাজি"),
    IslamicName("শাদিয়া", "আনন্দিত"),
    IslamicName("শাহদ", "মধু"),
    IslamicName("শাহনাজ", "রাজকীয় গর্ব"),
    IslamicName("শাইস্তা", "ভদ্র"),
    IslamicName("শিফা", "আরোগ্য"),
    IslamicName("তাকওয়া", "আল্লাহভীতি"),
    IslamicName("তামকিন", "মর্যাদা"),
    IslamicName("তানহা নূর", "একাকী আলো"),
    IslamicName("তাবিয়া", "অনুসরণকারী"),
    IslamicName("তাসফিয়া", "বিশুদ্ধতা"),
    IslamicName("তাহসিনা", "সুন্দর কাজ"),
    IslamicName("উম্মে হাবিবা", "প্রিয়জনের মা"),
    IslamicName("ইয়ুমনা", "সৌভাগ্যবতী"),
    IslamicName("ইয়ুসরা", "সহজতা"),
    IslamicName("জামিলা", "সুন্দরী"),
    IslamicName("ফারিহা", "আনন্দিত"),
    IslamicName("হাবিবা নূর", "প্রিয় আলো"),
    IslamicName("আনিয়া", "যত্নশীলা"),
    IslamicName("আরওয়া", "সুন্দরী, তৃপ্তিদায়ক"),
    IslamicName("আসমারা", "সুন্দর প্রজাপতি"),
    IslamicName("আফসানা নূর", "আলোর গল্প"),
    IslamicName("আফরিন", "প্রশংসা, অভিনন্দন"),
    IslamicName("আলিশা", "অভিজাত"),
    IslamicName("আমারা", "দীর্ঘজীবী"),
    IslamicName("আমানা", "বিশ্বাস, আমানত"),
    IslamicName("আনজিলা", "সম্মানিত নারী"),
    IslamicName("আরিবা জান্নাত", "জ্ঞানী জান্নাত"),
    IslamicName("আসরিন", "সুন্দর ও উজ্জ্বল"),
    IslamicName("আতিকা নূর", "সম্মানিত আলো"),
    IslamicName("আয়লা", "চাঁদের আলো"),
    IslamicName("আয়াত", "নিদর্শন, কুরআনের আয়াত"),
    IslamicName("আয়েশা সিদ্দিকা", "সত্যবাদী ও জীবন্ত"),
    IslamicName("বাদিয়া", "অদ্বিতীয়"),
    IslamicName("বানাফশা", "বেগুনি ফুল"),
    IslamicName("বাহিয়া", "সুন্দর ও উজ্জ্বল"),
    IslamicName("বিনতে হুদা", "হেদায়াতের কন্যা"),
    IslamicName("বুশাইরা", "সুসংবাদবাহক"),
    IslamicName("দানিয়া", "নিকটবর্তী, কোমল"),
    IslamicName("দুরদানা", "অমূল্য মুক্তা"),
    IslamicName("দিলআফরোজ", "হৃদয় আলোকিতকারী"),
    IslamicName("এশাল", "জান্নাতের ফুল"),
    IslamicName("ইনশা", "সৃষ্টি"),
    IslamicName("ইফরা", "সুখ দানকারী"),
    IslamicName("ইরাম", "জান্নাতের বাগান"),
    IslamicName("ইশা", "রাত্রি"),
    IslamicName("ইশমত আরা", "সতীত্বের অলংকার"),
    IslamicName("ইয়ামামা", "এক ধরনের পাখি"),
    IslamicName("জান্নাহ", "স্বর্গ"),
    IslamicName("জাওহারা", "মূল্যবান রত্ন"),
    IslamicName("জুমানা", "রূপার মুক্তা"),
    IslamicName("জারিয়া", "প্রবাহমান"),
    IslamicName("জাহানারা", "বিশ্বের অলংকার"),
    IslamicName("খায়রুন নিসা", "নারীদের মধ্যে উত্তম"),
    IslamicName("খুশবু", "সুগন্ধ"),
    IslamicName("খাদিজাতুল কুবরা", "মহান খাদিজা"),
    IslamicName("লামিস", "কোমল স্পর্শ"),
    IslamicName("লায়ান", "কোমলতা"),
    IslamicName("লিনা", "নরম খেজুর গাছ"),
    IslamicName("লুবাব", "বিশুদ্ধ নির্যাস"),
    IslamicName("মাদিহা", "প্রশংসাকারিণী"),
    IslamicName("মাহা", "বন্য হরিণী"),
    IslamicName("মাহবিশ", "চাঁদের মতো সুন্দর"),
    IslamicName("মাইমুনা", "সৌভাগ্যবতী"),
    IslamicName("মালাকা", "ফেরেশতা"),
    IslamicName("মারওয়াহ", "পবিত্র পাহাড়"),
    IslamicName("মেহবিশ", "চাঁদের আলো"),
    IslamicName("মিনহা", "আল্লাহর দান"),
    IslamicName("মুনাজ্জা", "পবিত্র"),
    IslamicName("মুনিরাহ", "উজ্জ্বল"),
    IslamicName("নাইলা", "সফলতা অর্জনকারী"),
    IslamicName("নাশিতা", "প্রাণবন্ত"),
    IslamicName("নাজিয়া", "মুক্তিপ্রাপ্ত"),
    IslamicName("নাহলা", "পানির প্রথম চুমুক"),
    IslamicName("নিদা", "আহ্বান"),
    IslamicName("নিমরা", "নরম স্বভাবের"),
    IslamicName("নূর ফাতিমা", "ফাতিমার আলো"),
    IslamicName("নূর সাবা", "সকালের আলো"),
    IslamicName("রাইদা নূর", "অগ্রগামী আলো"),
    IslamicName("রাফাহ", "সমৃদ্ধি"),
    IslamicName("রাবেয়া বসরী", "বিখ্যাত নারী সাধিকা"),
    IslamicName("রাহমা", "দয়া"),
    IslamicName("রিদওয়া", "সন্তুষ্টি"),
    IslamicName("রিমশা", "ফুলের তোড়া"),
    IslamicName("রুকাইয়াহ", "উন্নত মর্যাদা"),
    IslamicName("রুশদা", "সৎপথপ্রাপ্ত"),
    IslamicName("সাবিকা", "অগ্রগামী"),
    IslamicName("সাহারা", "ভোরের সময়"),
    IslamicName("সালিহা", "নেককার নারী"),
    IslamicName("সামিহা", "উদার"),
    IslamicName("সাবা নূর", "সকালের আলো"),
    IslamicName("সিদরাতুল মুনতাহা", "জান্নাতের বিশেষ বৃক্ষ"),
    IslamicName("সুমাইয়া নূর", "উচ্চ মর্যাদার আলো"),
    IslamicName("সুরাইয়া নূর", "তারকারাজির আলো"),
    IslamicName("শারমিলা", "লাজুক"),
    IslamicName("শারিকা", "অংশীদার"),
    IslamicName("শাহিনা আক্তার", "রাজকীয় তারা"),
    IslamicName("শিফাত", "গুণাবলী"),
    IslamicName("শুমাইলা", "সুন্দর চরিত্রের"),
    IslamicName("তাবাসসুম নূর", "হাসির আলো"),
    IslamicName("তানজিনা", "সুশৃঙ্খল"),
    IslamicName("তাসনীম জাহান", "জান্নাতের ঝর্ণা"),
    IslamicName("তাকিয়া", "ধার্মিক নারী"),
    IslamicName("তুবা", "জান্নাতের বৃক্ষ"),
    IslamicName("উম্মে সালমা", "সালমার মা"),
    IslamicName("উম্মে আইমান", "বিশ্বস্ততার মা"),
    IslamicName("ইয়াসমিনা", "জুঁই ফুল"),
    IslamicName("ইউসরাহ", "স্বাচ্ছন্দ্য"),
    IslamicName("ফারজানা", "বুদ্ধিমতী"),
    IslamicName("ফারিহাত", "আনন্দ"),
    IslamicName("হালা", "চাঁদের চারপাশের আলো"),
    IslamicName("হানান", "মমতা"),
    IslamicName("হুরিয়া", "জান্নাতের নারী"),
    IslamicName("হুমাইরা নূর", "লালাভ সুন্দরী আলো")
)
